// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// nuclearFPCA
Rcpp::List nuclearFPCA(List yList, List BList, arma::mat Omega, double lambda1, double lambda3);
RcppExport SEXP supern_nuclearFPCA(SEXP yListSEXP, SEXP BListSEXP, SEXP OmegaSEXP, SEXP lambda1SEXP, SEXP lambda3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type yList(yListSEXP);
    Rcpp::traits::input_parameter< List >::type BList(BListSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda3(lambda3SEXP);
    rcpp_result_gen = Rcpp::wrap(nuclearFPCA(yList, BList, Omega, lambda1, lambda3));
    return rcpp_result_gen;
END_RCPP
}
