# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nuclearFPCA <- function(yList, BList, Omega, lambda1, lambda3) {
    .Call('supern_nuclearFPCA', PACKAGE = 'supern', yList, BList, Omega, lambda1, lambda3)
}

